# -*- coding: utf-8 -*-
"""task 1 ,2 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z6bjeDQXwO0QDxDaj0svwYwa6a8F6aa8

---

## Section 1-B- Data loading

Similar to before, let's load our data from Google Drive for the 3 datasets provided. Be sure to upload the datasets into Google Drive, so that you can access them here.
"""

#path = "C:\Users\Atreyee\Desktop\Hackfest\sales(1).csv"
import pandas as pd
sales_df = pd.read_csv("sales(1).csv")
sales_df.drop(columns=["Unnamed: 0"], inplace=True, errors='ignore')
sales_df.head()





stock_df = pd.read_csv("sensor_stock_levels (1).csv")
stock_df.drop(columns=["Unnamed: 0"], inplace=True, errors='ignore')
stock_df.head()

temp_df = pd.read_csv("sensor_storage_temperature (1).csv")
temp_df.drop(columns=["Unnamed: 0"], inplace=True, errors='ignore')
temp_df.head()

"""---

## Section 1-c - Data cleaning

Now that we have our 3 datasets successfully loaded, we need to ensure that the data is clean. Data cleaning can be a very intense task, so for this exercise, we will focus just on ensuring that the correct datatypes are present for each column, and if not, correcting them.

We can use the `.info()` method to look at data types.
"""

sales_df.info()

stock_df.info()

temp_df.info()

"""Everything looks fine for the 3 datasets apart from the `timestamp` column in each dataset. Using the same helper function as before, let's convert this to the correct type for each dataset."""

def convert_to_datetime(data: pd.DataFrame = None, column: str = None):

  dummy = data.copy()
  dummy[column] = pd.to_datetime(dummy[column], format='%Y-%m-%d %H:%M:%S')
  return dummy

sales_df = convert_to_datetime(sales_df, 'timestamp')
sales_df.info()

stock_df = convert_to_datetime(stock_df, 'timestamp')
stock_df.info()

temp_df = convert_to_datetime(temp_df, 'timestamp')
temp_df.info()

"""This looks much better!

---

## Section 1-D - Merge data

Currently we have 3 datasets. In order to include all of this data within a predictive model, we need to merge them together into 1 dataframe.

If we revisit the problem statement:

```
“Can we accurately predict the stock levels of products, based on sales data and sensor data,
on an hourly basis in order to more intelligently procure products from our suppliers.”
```

The client indicates that they want the model to predict on an hourly basis. Looking at the data model, we can see that only column that we can use to merge the 3 datasets together is `timestamp`.

So, we must first transform the `timestamp` column in all 3 datasets to be based on the hour of the day, then we can merge the datasets together.
"""

sales_df.head()

from datetime import datetime

def convert_timestamp_to_hourly(data: pd.DataFrame = None, column: str = None):
  dummy = data.copy()
  new_ts = dummy[column].tolist()
  new_ts = [i.strftime('%Y-%m-%d %H:00:00') for i in new_ts]
  new_ts = [datetime.strptime(i, '%Y-%m-%d %H:00:00') for i in new_ts]
  dummy[column] = new_ts
  return dummy

sales_df = convert_timestamp_to_hourly(sales_df, 'timestamp')
sales_df.head()

stock_df = convert_timestamp_to_hourly(stock_df, 'timestamp')
stock_df.head()

temp_df = convert_timestamp_to_hourly(temp_df, 'timestamp')
temp_df.head()

"""Now you can see all of the `timestamp` columns have had the minutes and seconds reduced to `00`. The next thing to do, is to aggregate the datasets in order to combine rows which have the same value for `timestamp`.

For the `sales` data, we want to group the data by `timestamp` but also by `product_id`. When we aggregate, we must choose which columns to aggregate by the grouping. For now, let's aggregate quantity.
"""

sales_agg = sales_df.groupby(['timestamp', 'product_id']).agg({'quantity': 'sum'}).reset_index()
sales_agg.head()

"""We now have an aggregated sales data where each row represents a unique combination of hour during which the sales took place from that weeks worth of data and the product_id. We summed the quantity and we took the mean average of the unit_price.

For the stock data, we want to group it in the same way and aggregate the `estimated_stock_pct`.
"""

stock_agg = stock_df.groupby(['timestamp', 'product_id']).agg({'estimated_stock_pct': 'mean'}).reset_index()
stock_agg.head()

"""This shows us the average stock percentage of each product at unique hours within the week of sample data.

Finally, for the temperature data, product_id does not exist in this table, so we simply need to group by timestamp and aggregate the `temperature`.
"""

temp_agg = temp_df.groupby(['timestamp']).agg({'temperature': 'mean'}).reset_index()
temp_agg.head()

"""This gives us the average temperature of the storage facility where the produce is stored in the warehouse by unique hours during the week. Now, we are ready to merge our data. We will use the `stock_agg` table as our base table, and we will merge our other 2 tables onto this."""

merged_df = stock_agg.merge(sales_agg, on=['timestamp', 'product_id'], how='left')
merged_df.head()

merged_df = merged_df.merge(temp_agg, on='timestamp', how='left')
merged_df.head()

merged_df.info()

"""We can see from the `.info()` method that we have some null values. These need to be treated before we can build a predictive model. The column that features some null values is `quantity`. We can assume that if there is a null value for this column, it represents that there were 0 sales of this product within this hour. So, lets fill this columns null values with 0, however, we should verify this with the client, in order to make sure we're not making any assumptions by filling these null values with 0."""

merged_df['quantity'] = merged_df['quantity'].fillna(0)
merged_df.info()

"""We can combine some more features onto this table too, including `category` and `unit_price`."""

product_categories = sales_df[['product_id', 'category']]
product_categories = product_categories.drop_duplicates()

product_price = sales_df[['product_id', 'unit_price']]
product_price = product_price.drop_duplicates()

merged_df = merged_df.merge(product_categories, on="product_id", how="left")
merged_df.head()

merged_df = merged_df.merge(product_price, on="product_id", how="left")
merged_df.head()

merged_df.info()

"""Now we have our table with 2 extra features!

---

## Section 1-E - Feature engineering

We have our cleaned and merged data. Now we must transform this data so that the columns are in a suitable format for a machine learning model. In other terms, every column must be numeric. There are some models that will accept categorical features, but for this exercise we will use a model that requires numeric features.

Let's first engineer the `timestamp` column. In it's current form, it is not very useful for a machine learning model. Since it's a datetime datatype, we can explode this column into day of week, day of month and hour to name a few.
"""

merged_df['timestamp_day_of_month'] = merged_df['timestamp'].dt.day
merged_df['timestamp_day_of_week'] = merged_df['timestamp'].dt.dayofweek
merged_df['timestamp_hour'] = merged_df['timestamp'].dt.hour
merged_df.drop(columns=['timestamp'], inplace=True)
merged_df.head()

"""The next column that we can engineer is the `category` column. In its current form it is categorical. We can convert it into numeric by creating dummy variables from this categorical column.

A dummy variable is a binary flag column (1's and 0's) that indicates whether a row fits a particular value of that column. For example, we can create a dummy column called category_pets, which will contain a 1 if that row indicates a product which was included within this category and a 0 if not.
"""

merged_df = pd.get_dummies(merged_df, columns=['category'])
merged_df.head()

merged_df.info()

"""Looking at the latest table, we only have 1 remaining column which is not numeric. This is the `product_id`.

Since each row represents a unique combination of product_id and timestamp by hour, and the product_id is simply an ID column, it will add no value by including it in the predictive model. Hence, we shall remove it from the modeling process.
"""

merged_df.drop(columns=['product_id'], inplace=True)
merged_df.head()

sales_data = pd.DataFrame(merged_df)

"""### Section 2"""

sales_data['sales_revenue'] = sales_data['quantity'] * sales_data['unit_price']

total_revenue = sales_data['sales_revenue'].sum()

sales_data['market_share'] = sales_data['sales_revenue'] / total_revenue

category_columns = sales_data.columns[sales_data.columns.str.startswith('category_')]

sales_data['product_category'] = sales_data[category_columns].idxmax(axis=1)

category_sales_revenue = sales_data.groupby('product_category')['sales_revenue'].sum()

best_category = category_sales_revenue.idxmax()
worst_category = category_sales_revenue.idxmin()

category_sales_revenue = sales_data.groupby('product_category')['sales_revenue'].sum()
best_category = category_sales_revenue.idxmax()
worst_category = category_sales_revenue.idxmin()

sales_data['timestamp'] = pd.to_datetime(sales_data['timestamp_hour'])
sales_data = sales_data.sort_values(by='timestamp')
sales_data['growth_rate'] = sales_data.groupby('product_category')['sales_revenue'].diff() / sales_data.groupby('product_category')['sales_revenue'].shift()

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 12))
category_sales_revenue.plot(kind='bar', color='skyblue')
plt.title('Sales Revenue by Product Category')
plt.xlabel('Product Category')
plt.ylabel('Sales Revenue')
plt.xticks(rotation=90)
plt.show()

print("Best-performing category:", best_category)
print("Worst-performing category:", worst_category)

"""### Section 3"""

key_attributes = ['unit_price', 'category_packaged foods', 'category_brand', 'category_distribution_channel', 'category_consumer_demographics']

best_category_data = sales_data[sales_data['product_category'] == best_category]
worst_category_data = sales_data[sales_data['product_category'] == worst_category]

best_category_data

best_category_summary = best_category_data[['unit_price', 'estimated_stock_pct']].describe()
worst_category_summary = worst_category_data[['unit_price', 'estimated_stock_pct']].describe()

print("Summary Statistics for Best Performing Category:")
print(best_category_summary)
print("\nSummary Statistics for Worst Performing Category:")
print(worst_category_summary)

plt.figure(figsize=(10, 6))
plt.subplot(1, 2, 1)
plt.boxplot([best_category_data['unit_price'], worst_category_data['unit_price']], labels=['Best Category', 'Worst Category'])
plt.title('Unit Price Comparison')
plt.ylabel('Unit Price')

plt.subplot(1, 2, 2)
plt.boxplot([best_category_data['estimated_stock_pct'], worst_category_data['estimated_stock_pct']], labels=['Best Category', 'Worst Category'])
plt.title('Estimated Stock Percentage Comparison')
plt.ylabel('Estimated Stock Percentage')

plt.tight_layout()
plt.show()

category_sales_revenue = sales_data.groupby('product_category')['sales_revenue'].sum()
best_category = category_sales_revenue.idxmax()
worst_category = category_sales_revenue.idxmin()

best_category_data = sales_data[sales_data['product_category'] == best_category]
worst_category_data = sales_data[sales_data['product_category'] == worst_category]

price_stats_best = best_category_data['unit_price'].describe()
price_stats_worst = worst_category_data['unit_price'].describe()


stock_stats_best = best_category_data['estimated_stock_pct'].describe()
stock_stats_worst = worst_category_data['estimated_stock_pct'].describe()


quantity_stats_best = best_category_data['quantity'].describe()
quantity_stats_worst = worst_category_data['quantity'].describe()


if 'temperature' in sales_data.columns:
    temp_stats_best = best_category_data['temperature'].describe()
    temp_stats_worst = worst_category_data['temperature'].describe()

time_trends_best = best_category_data.groupby('timestamp_day_of_week')['quantity'].mean()
time_trends_worst = worst_category_data.groupby('timestamp_day_of_week')['quantity'].mean()

def extract_packaging(row):
    packaging_categories = ['category_packaged foods', 'category_canned foods', 'category_refrigerated items', 'category_dairy']
    for category in packaging_categories:
        if row[category]:
            return 1
    return 0
sales_data['packaging'] = sales_data.apply(extract_packaging, axis=1)

def extract_branding(row):
    branding_categories = ['category_beverages', 'category_condiments and sauces', 'category_snacks']
    for category in branding_categories:
        if row[category]:
            return 1
    return 0

sales_data['branding'] = sales_data.apply(extract_packaging, axis=1)

plt.figure(figsize=(10, 6))
plt.subplot(2, 2, 1)
best_category_data['unit_price'].plot(kind='hist', bins=20, color='blue', alpha=0.5, label='Best Category')
worst_category_data['unit_price'].plot(kind='hist', bins=20, color='red', alpha=0.5, label='Worst Category')
plt.xlabel('Unit Price')
plt.ylabel('Frequency')
plt.title('Price Point Distribution')
plt.legend()

plt.subplot(2, 2, 2)
best_category_data['estimated_stock_pct'].plot(kind='hist', bins=20, color='blue', alpha=0.5, label='Best Category')
worst_category_data['estimated_stock_pct'].plot(kind='hist', bins=20, color='red', alpha=0.5, label='Worst Category')
plt.xlabel('Estimated Stock Percentage')
plt.ylabel('Frequency')
plt.title('Estimated Stock Percentage Distribution')
plt.legend()

plt.subplot(2, 2, 3)
best_category_data['quantity'].plot(kind='hist', bins=20, color='blue', alpha=0.5, label='Best Category')
worst_category_data['quantity'].plot(kind='hist', bins=20, color='red', alpha=0.5, label='Worst Category')
plt.xlabel('Quantity Sold')
plt.ylabel('Frequency')
plt.title('Quantity Sold Distribution')
plt.legend()

plt.subplot(2, 2, 4)
time_trends_best.plot(kind='line', marker='o', color='blue', label='Best Category')
time_trends_worst.plot(kind='line', marker='o', color='red', label='Worst Category')
plt.xlabel('Day of Week')
plt.ylabel('Average Quantity Sold')
plt.title('Average Quantity Sold by Day of Week')
plt.xticks(range(7), ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'])
plt.legend()

plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 6))
sales_data['packaging'].value_counts().plot(kind='bar', color='skyblue')
plt.title('Distribution of Packaging Types')
plt.xlabel('Packaging Type')
plt.ylabel('Count')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

# Branding Presence
plt.figure(figsize=(6, 6))
sales_data['branding'].value_counts().plot(kind='pie', autopct='%1.1f%%', colors=['lightcoral', 'lightgreen'])
plt.title('Branding Presence')
plt.ylabel('')
plt.axis('equal')
plt.tight_layout()
plt.show()

sales_data.info()



"""### Section 4

#### Sales Trends Over Time

##### The interactive line chart below illustrates the sales trends over time, showcasing the overall revenue trajectory for Marico Ltd.
##### Users can hover over data points to view specific sales figures for each timestamp.
"""

import plotly.express as px

fig = px.line(sales_data, x='timestamp', y='sales_revenue', title='Sales Trends Over Time')
fig.show()

"""#### Sales Revenue by Product Category

##### The bar chart below compares sales revenue across different product categories, providing insights into the performance of each category.
##### Users can use the dropdown menu to select specific product categories for comparison.
"""

fig = px.bar(sales_data, x='product_category', y='sales_revenue', title='Sales Revenue by Product Category')
fig.show()



"""This feature engineering was by no means exhaustive, but was enough to give you an example of the process followed when engineering the features of a dataset. In reality, this is an iterative task. Once you've built a model, you may have to revist feature engineering in order to create new features to boost the predictive power of a machine learning model.

---

## Section 7 - Modelling

Now it is time to train a machine learning model. We will use a supervised machine learning model, and we will use `estimated_stock_pct` as the target variable, since the problem statement was focused on being able to predict the stock levels of products on an hourly basis.

Whilst training the machine learning model, we will use cross-validation, which is a technique where we hold back a portion of the dataset for testing in order to compute how well the trained machine learning model is able to predict the target variable.

Finally, to ensure that the trained machine learning model is able to perform robustly, we will want to test it several times on random samples of data, not just once. Hence, we will use a `K-fold` strategy to train the machine learning model on `K` (K is an integer to be decided) random samples of the data.

First, let's create our target variable `y` and independent variables `X`
"""

sales_data.info()

sales_data.to_csv('sales_data.csv',index = False)

import tkinter as tk
from tkinter import ttk

class AnalysisInterface:
    def __init__(self, root):
        self.root = root
        self.root.title("Analysis Interface")

        # Create frames for different sections
        self.parameters_frame = tk.Frame(self.root)
        self.parameters_frame.pack(fill="x")

        self.visualization_frame = tk.Frame(self.root)
        self.visualization_frame.pack(fill="x")

        self.schedule_frame = tk.Frame(self.root)
        self.schedule_frame.pack(fill="x")

        # Create labels and entries for parameters
        self.parameters_labels = []
        self.parameters_entries = []
        for i in range(5):
            label = tk.Label(self.parameters_frame, text=f"Parameter {i+1}:")
            label.pack(side="left")
            entry = tk.Entry(self.parameters_frame, width=20)
            entry.pack(side="left")
            self.parameters_labels.append(label)
            self.parameters_entries.append(entry)

        # Create radio buttons for visualization options
        self.visualization_options = ["Bar Chart", "Line Chart", "Scatter Plot"]
        self.visualization_var = tk.StringVar()
        self.visualization_var.set(self.visualization_options[0])
        for option in self.visualization_options:
            radio_button = ttk.Radiobutton(self.visualization_frame, text=option, variable=self.visualization_var, value=option)
            radio_button.pack(side="left")

        # Create buttons for scheduling
        self.schedule_button = tk.Button(self.schedule_frame, text="Schedule Report", command=self.schedule_report)
        self.schedule_button.pack(side="left")

    def schedule_report(self):
        # Get the parameters and visualization option from the interface
        parameters = [entry.get() for entry in self.parameters_entries]
        visualization_option = self.visualization_var.get()

        # Perform the analysis and generate the report
        # ...

        # Schedule the report generation
        import schedule
        import time
        def generate_report():
            # Perform the analysis and generate the report
            # ...
            schedule.every(1).day.at("08:00").do(generate_report)  # Run the report every day at 8:00 AM
        while True:
            schedule.run_pending()
            time.sleep(1)

if __name__ == "__main__":
    root = tk.Tk()
    interface = AnalysisInterface(root)
    root.mainloop()







X = merged_df.drop(columns=['estimated_stock_pct'])
y = merged_df['estimated_stock_pct']
print(X.shape)
print(y.shape)

"""This shows that we have 29 predictor variables that we will train our machine learning model on and 10845 rows of data.

Now let's define how many folds we want to complete during training, and how much of the dataset to assign to training, leaving the rest for test.

Typically, we should leave at least 20-30% of the data for testing.
"""

K = 10
split = 0.75

"""For this exercise, we are going to use a `RandomForestRegressor` model, which is an instance of a Random Forest. These are powerful tree based ensemble algorithms and are particularly good because their results are very interpretable.

We are using a `regression` algorithm here because we are predicting a continuous numeric variable, that is, `estimated_stock_pct`. A `classification` algorithm would be suitable for scenarios where you're predicted a binary outcome, e.g. True/False.

We are going to use a package called `scikit-learn` for the machine learning algorithm, so first we must install and import this, along with some other functions and classes that can help with the evaluation of the model.
"""

!pip install scikit-learn

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
from sklearn.preprocessing import StandardScaler

"""And now let's create a loop to train `K` models with a 75/25% random split of the data each time between training and test samples"""

accuracy = []

for fold in range(0, K):

  # Instantiate algorithm
  model = RandomForestRegressor()
  scaler = StandardScaler()

  # Create training and test samples
  X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=split, random_state=42)

  # Scale X data, we scale the data because it helps the algorithm to converge
  # and helps the algorithm to not be greedy with large values
  scaler.fit(X_train)
  X_train = scaler.transform(X_train)
  X_test = scaler.transform(X_test)

  # Train model
  trained_model = model.fit(X_train, y_train)

  # Generate predictions on test sample
  y_pred = trained_model.predict(X_test)

  # Compute accuracy, using mean absolute error
  mae = mean_absolute_error(y_true=y_test, y_pred=y_pred)
  accuracy.append(mae)
  print(f"Fold {fold + 1}: MAE = {mae:.3f}")

print(f"Average MAE: {(sum(accuracy) / len(accuracy)):.2f}")

"""Note, the output of this training loop may be slightly different for you if you have prepared the data differently or used different parameters!

This is very interesting though. We can see that the `mean absolute error` (MAE) is almost exactly the same each time. This is a good sign, it shows that the performance of the model is consistent across different random samples of the data, which is what we want. In other words, it shows a robust nature.

The `MAE` was chosen as a performance metric because it describes how closely the machine learning model was able to predict the exact value of `estimated_stock_pct`.

Even though the model is predicting robustly, this value for MAE is not so good, since the average value of the target variable is around 0.51, meaning that the accuracy as a percentage was around 50%. In an ideal world, we would want the MAE to be as low as possible. This is where the iterative process of machine learning comes in. At this stage, since we only have small samples of the data, we can report back to the business with these findings and recommend that the the dataset needs to be further engineered, or more datasets need to be added.

As a final note, we can use the trained model to intepret which features were signficant when the model was predicting the target variable. We will use `matplotlib` and `numpy` to visualuse the results, so we should install and import this package.
"""

!pip install matplotlib
!pip install numpy

import matplotlib.pyplot as plt
import numpy as np

features = [i.split("__")[0] for i in X.columns]
importances = model.feature_importances_
indices = np.argsort(importances)

fig, ax = plt.subplots(figsize=(10, 20))
plt.title('Feature Importances')
plt.barh(range(len(indices)), importances[indices], color='b', align='center')
plt.yticks(range(len(indices)), [features[i] for i in indices])
plt.xlabel('Relative Importance')
plt.show()

"""This feature importance visualisation tells us:

- The product categories were not that important
- The unit price and temperature were important in predicting stock
- The hour of day was also important for predicting stock

With these insights, we can now report this back to the business
"""

